### ISSUE TITLE
pure_location Loadmap time cost  6 second?

### ISSUE THREAD

**Issue by xuguangyun** [googlecartographer/cartographer#743] opened 2017-12-07 11:57 UTC
I have compile the Cartographer with Debug and run it. But there have some issue:  Loadmap function cost about 6 second (the map size 19M)  and terminal out isnot normal,as this:
![8t171mep 02y1vcgo5j y 3](https://user-images.githubusercontent.com/6286367/33714131-dc44ce0e-db88-11e7-9bc7-acfa85b20192.png)

**Comment by gaschler** [comment] 2017-12-07 12:31
Yes, debug mode is really inefficient. The terminal output tells the same.
If you need debug symbols, please compile with CMAKE_BUILD_TYPE=RelWithDebInfo.
Closing because it works as intended.

**Closed by gaschler** 2017-12-07 12:31 UTC

**Comment by xuguangyun** [comment] 2017-12-08 00:24
Hi gaschler,thanks a lot.As you say i compile with CMAKE_BUILD_TYPE=RelWithDebInfo but it turn out to be  the same ..

**Comment by xuguangyun** [comment] 2017-12-08 05:13
solved.Same like gaschler say.but i donot know why the CMAKE_BUILD_TYPE=RelWithDebInfo do not work.
i have to use add the command   -std=gnu++11  -O3 .
