### ISSUE TITLE
Cartographer worse than Gmapping

### ISSUE THREAD

**Issue by nangong** [googlecartographer/cartographer#202] opened 2017-02-09 06:29 UTC
Launch file, Bag ,Configuration is [here](https://drive.google.com/open?id=0Bz4iO_gw1vXSX3lLYnZGdzBoLVE).

I tested the same bag file in gmapping and cartographer.  The two results are listed as follows,

Cartographer,
![image](https://cloud.githubusercontent.com/assets/2638853/22771620/d0a158b8-eed2-11e6-865a-cdfa2c0813e4.png)

Just like I mentioned in #190 , the loop closure detection did not work.

Gmapping(which is very similar to the real environment),
![image](https://cloud.githubusercontent.com/assets/2638853/22771664/21a5b506-eed3-11e6-9a81-02af764db1b4.png)

Since I had already combined imu data into odom(/odometry/filtered in the ros bag), I did not provide the raw imu data(/costly_imu in the ros bag) to both slam.

Would you @SirVer  please tell what should I do next?

Thanks very much.

**Comment by SirVer** [comment] 2017-02-09 09:51
Your statement is that default settings are better than default settings of Cartographer? That seems unsurprising. What did you try to tune already? Have you tried disabling your IMU/odom merged topic and only use scan matching as I suggested in https://github.com/googlecartographer/cartographer_ros/issues/249?

**Comment by nangong** [comment] 2017-02-10 08:50
Thanks for replying so fast.

I tracked the odom trajectory and it was accurate in most time.

 After comparing the mapping progress between Gmapping and Cartographer, I found the problem was caused by what you alerted me in #190 ,i.e. my laser is not always level, it is fixed on the robot and the floor has tiny pitches in the following part,

![image](https://cloud.githubusercontent.com/assets/2638853/22820242/dc240b98-efb0-11e6-93c1-1be882c5bb62.png)

Is that possible to fix this by tunning any parameters (e.g. increasing confidence of odom)?

**Comment by SirVer** [comment] 2017-02-10 10:02
> Is that possible to fix this by tunning any parameters (e.g. increasing confidence of odom)?

You can tune of course, but it is hard to say if this is fixable from just the image. If your sensors are strongly disagreeing, there will be no real way to fix the issue. If you trust odom so significanlty more than the laser and it has a bias (which it likely has), you will mess up other parts of the map.

I tried looking at your bag and configuration. But I do not have access to the drive elements. Also, make sure that your bag already contains the always-level laser changes.

**Comment by nangong** [comment] 2017-02-10 13:53
Sorry, I forgot to enable others to access the drive. It can be downloaded now.

**Comment by alexbaucom17** [comment] 2017-02-28 14:25
I am running into a similar problem where the loop closure is poor in indoor environments. I am using a laser, odom, and an IMU. The floor I am mapping also has small bumps and the robot does not always stay level. If I am providing IMU data should cartographer handle this okay? Or do I need to do some pre-processing on the laser data?

**Comment by SirVer** [comment] 2017-03-01 12:59
@alexbaucom17 It probably also just comes down to tuning. Sometimes IMU jumps over bumps are extreme and throw off the SLAM - then it might be better to disable IMU and use correlative scan (see closed issues labeled tuning for ideas.)

**Comment by alexbaucom17** [comment] 2017-03-01 13:02
Got it. I will do some more testing and tuning then. Thanks.

**Comment by SirVer** [comment] 2017-03-02 12:21
@nangong I found some time to look at this now. Unsorted comments:

- Your launch file refers to `demo_husky.lua` which you did not include. I used `demo_myrobot.lua` instead. 
- You also didn't include `demo_myrobot.rviz`. 
- Your configuration files have gone out of sync with HEAD, i.e. some options have vanished or have been renamed.
- You did not include a URDF and your bag contains TF information from another SLAM run - so I could not use that either. This means I cannot spatially relate your odom or IMU data to your laser data - I therefore disabled both odometry and IMU.

It would have been nicer to have a proper git fork with all files so I could reproduce on exactly your conditions - you it pretty hard for me to help you :(.

- Your outdoor (?) area that connects the two rooms the robot drives into seems to violate the 2D assumptions (i.e. flat floor, mostly orthogonal objects). Even to me as a human the laser clouds seem very different on the way back than they look on the way there.
- Sometimes your laser only sees very far away objects. Your configuration before threw away everything farther away than 30m, so there was no information for SLAM. 
- With your laser's poor angular resolution and high noise you cannot expect to SLAM at 5cm if your objects are so far away - your points visible jump by 15-30cm. I set the resolution to 15cm and that seemed to be sufficient to capture this.

My final settings drift by ~1.5m after the long loop (comping back to the first building) which is fixed by loop closure. Image attached below. I think adding IMU + odometry might increase performance (i.e. require less CPU) since you might get away without the correlative_scan_matcher, but this will probably  not improve quality.

The middle part of the map is still wrong. But I cannot blame SLAM there, the data is not looking consistent as mentioned above. This claim is supported that after loop closure both building parts are very good, but the middle part is still inconsistent - this is really only possible if the data is inconsistent there because everything is the same optimization problem.

My changes are [in this branch](https://github.com/SirVer/cartographer_ros/tree/user/nangong) in the last few commits.

![demo_myrobot](https://cloud.githubusercontent.com/assets/140115/23506843/8a1d89b0-ff4a-11e6-8ae0-275f4a612a54.png)

**Closed by SirVer** 2017-03-02 12:21 UTC
Labels: tuning

**Comment by nangong** [comment] 2017-03-03 11:05
Got it..
Thanks very much for your help... : )

**Comment by ahmdsamy** [comment] 2017-04-20 15:15
@nangong  @SirVer I am using RPlidar which have a 6m range only .. and i am getting visual odometry from ZED camera, and the odom is very accurate.. how can i increase the odom confidence as you were saying in the upper comments ?

**Comment by alexbaucom17** [comment] 2017-04-20 16:41
@ahmdsamy They showed me how to change odometry confidence in [this issue](https://github.com/googlecartographer/cartographer_turtlebot/issues/48). You can look at the comments in the config file of my fork.
