### ISSUE TITLE
Node pruning for long-term SLAM ?

### ISSUE THREAD

**Issue by Hui-Lin** [googlecartographer/cartographer#445] opened 2017-08-10 03:07 UTC
Hi there, I just tried the version #438  of cartographer, and it's amazing to serialize the pose graph for saving and restoring for long-term mapping. However I noticed that the number of nodes and edges of the pose graph grows rapidly with time, even in the situation of robot revisiting the known area, which causes more and more memory and computation cost. Is there any plan for node pruning to maintain the sparsity of pose graph ?

Best regards.

**Comment by damonkohler** [comment] 2017-08-10 06:53
What you're describing we call life-long SLAM. It is a goal were actively working towards. See #409. I'm closing this as a duplicate of that issue.

**Closed by damonkohler** 2017-08-10 06:53 UTC
