### ISSUE TITLE
PosewithCovariance cartographer

### ISSUE THREAD

**Issue by alfred31** [googlecartographer/cartographer#1469] opened 2018-11-27 13:24 UTC
Hello,

First of all thanks for the amazing job you've done.

Now that I've tuned cartographer and it is working incredibly precise, I want to get a pose topic to get the localization of the robot. I have already made a ros node that publishes a geometry_msgs::PoseStamped message, but what I really want to get is a geometry_msgs::PoseWithCovariance.

The point is that I don't know how I can defined this covariance, Is there any way to get this covariance in the cartographer, or at least a way to approximate it?

Thank you very much.

Kind Regards

**Comment by gaschler** [comment] 2018-11-30 14:02
closing duplicate of https://github.com/googlecartographer/cartographer_ros/issues/1109

**Closed by gaschler** 2018-11-30 14:02 UTC
